# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGui\form.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_heartUI(object):
    def setupUi(self, heartUI):
        heartUI.setObjectName("heartUI")
        heartUI.resize(813, 1010)
        self.centralwidget = QtWidgets.QWidget(heartUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelSelectModel = QtWidgets.QLabel(self.centralwidget)
        self.labelSelectModel.setObjectName("labelSelectModel")
        self.horizontalLayout.addWidget(self.labelSelectModel)
        self.selectModelBox = QtWidgets.QComboBox(self.centralwidget)
        self.selectModelBox.setEnabled(False)
        self.selectModelBox.setObjectName("selectModelBox")
        self.selectModelBox.addItem("")
        self.selectModelBox.addItem("")
        self.selectModelBox.addItem("")
        self.selectModelBox.addItem("")
        self.selectModelBox.addItem("")
        self.horizontalLayout.addWidget(self.selectModelBox)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnRez = QtWidgets.QPushButton(self.centralwidget)
        self.btnRez.setObjectName("btnRez")
        self.horizontalLayout_7.addWidget(self.btnRez)
        self.l_rez = QtWidgets.QLabel(self.centralwidget)
        self.l_rez.setWordWrap(True)
        self.l_rez.setObjectName("l_rez")
        self.horizontalLayout_7.addWidget(self.l_rez)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.rb_manual = QtWidgets.QRadioButton(self.groupBox)
        self.rb_manual.setChecked(False)
        self.rb_manual.setObjectName("rb_manual")
        self.buttonGroup = QtWidgets.QButtonGroup(heartUI)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rb_manual)
        self.horizontalLayout_28.addWidget(self.rb_manual)
        self.rb_console = QtWidgets.QRadioButton(self.groupBox)
        self.rb_console.setChecked(True)
        self.rb_console.setObjectName("rb_console")
        self.buttonGroup.addButton(self.rb_console)
        self.horizontalLayout_28.addWidget(self.rb_console)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_28)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.gb_manual = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_manual.setEnabled(False)
        self.gb_manual.setObjectName("gb_manual")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.gb_manual)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_area = QtWidgets.QLabel(self.gb_manual)
        self.label_area.setObjectName("label_area")
        self.horizontalLayout_2.addWidget(self.label_area)
        self.cb_area = QtWidgets.QComboBox(self.gb_manual)
        self.cb_area.setObjectName("cb_area")
        self.cb_area.addItem("")
        self.cb_area.addItem("")
        self.horizontalLayout_2.addWidget(self.cb_area)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_sex = QtWidgets.QLabel(self.gb_manual)
        self.label_sex.setObjectName("label_sex")
        self.horizontalLayout_3.addWidget(self.label_sex)
        self.cb_sex = QtWidgets.QComboBox(self.gb_manual)
        self.cb_sex.setObjectName("cb_sex")
        self.cb_sex.addItem("")
        self.cb_sex.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_sex)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_steno = QtWidgets.QLabel(self.gb_manual)
        self.label_steno.setWordWrap(True)
        self.label_steno.setObjectName("label_steno")
        self.horizontalLayout_4.addWidget(self.label_steno)
        self.cb_steno = QtWidgets.QComboBox(self.gb_manual)
        self.cb_steno.setObjectName("cb_steno")
        self.cb_steno.addItem("")
        self.cb_steno.addItem("")
        self.horizontalLayout_4.addWidget(self.cb_steno)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_othHeartDes = QtWidgets.QLabel(self.gb_manual)
        self.label_othHeartDes.setWordWrap(True)
        self.label_othHeartDes.setObjectName("label_othHeartDes")
        self.horizontalLayout_5.addWidget(self.label_othHeartDes)
        self.cb_othHearDes = QtWidgets.QComboBox(self.gb_manual)
        self.cb_othHearDes.setObjectName("cb_othHearDes")
        self.cb_othHearDes.addItem("")
        self.cb_othHearDes.addItem("")
        self.horizontalLayout_5.addWidget(self.cb_othHearDes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_heartNed = QtWidgets.QLabel(self.gb_manual)
        self.label_heartNed.setWordWrap(True)
        self.label_heartNed.setObjectName("label_heartNed")
        self.horizontalLayout_6.addWidget(self.label_heartNed)
        self.cb_heartNed = QtWidgets.QComboBox(self.gb_manual)
        self.cb_heartNed.setObjectName("cb_heartNed")
        self.cb_heartNed.addItem("")
        self.cb_heartNed.addItem("")
        self.horizontalLayout_6.addWidget(self.cb_heartNed)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_artHyper = QtWidgets.QLabel(self.gb_manual)
        self.label_artHyper.setWordWrap(True)
        self.label_artHyper.setObjectName("label_artHyper")
        self.horizontalLayout_9.addWidget(self.label_artHyper)
        self.cb_artHyper = QtWidgets.QComboBox(self.gb_manual)
        self.cb_artHyper.setObjectName("cb_artHyper")
        self.cb_artHyper.addItem("")
        self.cb_artHyper.addItem("")
        self.horizontalLayout_9.addWidget(self.cb_artHyper)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_educ = QtWidgets.QLabel(self.gb_manual)
        self.label_educ.setWordWrap(True)
        self.label_educ.setObjectName("label_educ")
        self.horizontalLayout_10.addWidget(self.label_educ)
        self.cb_educ = QtWidgets.QComboBox(self.gb_manual)
        self.cb_educ.setObjectName("cb_educ")
        self.cb_educ.addItem("")
        self.cb_educ.addItem("")
        self.cb_educ.addItem("")
        self.cb_educ.addItem("")
        self.horizontalLayout_10.addWidget(self.cb_educ)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_ecgNorm = QtWidgets.QLabel(self.gb_manual)
        self.label_ecgNorm.setWordWrap(True)
        self.label_ecgNorm.setObjectName("label_ecgNorm")
        self.horizontalLayout_11.addWidget(self.label_ecgNorm)
        self.cb_ecgNorm = QtWidgets.QComboBox(self.gb_manual)
        self.cb_ecgNorm.setObjectName("cb_ecgNorm")
        self.cb_ecgNorm.addItem("")
        self.cb_ecgNorm.addItem("")
        self.horizontalLayout_11.addWidget(self.cb_ecgNorm)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_regularDrug = QtWidgets.QLabel(self.gb_manual)
        self.label_regularDrug.setWordWrap(True)
        self.label_regularDrug.setObjectName("label_regularDrug")
        self.horizontalLayout_12.addWidget(self.label_regularDrug)
        self.cb_regularDrug = QtWidgets.QComboBox(self.gb_manual)
        self.cb_regularDrug.setObjectName("cb_regularDrug")
        self.cb_regularDrug.addItem("")
        self.cb_regularDrug.addItem("")
        self.horizontalLayout_12.addWidget(self.cb_regularDrug)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_sugDiab = QtWidgets.QLabel(self.gb_manual)
        self.label_sugDiab.setWordWrap(True)
        self.label_sugDiab.setObjectName("label_sugDiab")
        self.horizontalLayout_13.addWidget(self.label_sugDiab)
        self.cb_sugDiab = QtWidgets.QComboBox(self.gb_manual)
        self.cb_sugDiab.setObjectName("cb_sugDiab")
        self.cb_sugDiab.addItem("")
        self.cb_sugDiab.addItem("")
        self.horizontalLayout_13.addWidget(self.cb_sugDiab)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_hepatit = QtWidgets.QLabel(self.gb_manual)
        self.label_hepatit.setWordWrap(True)
        self.label_hepatit.setObjectName("label_hepatit")
        self.horizontalLayout_14.addWidget(self.label_hepatit)
        self.cb__hepatit = QtWidgets.QComboBox(self.gb_manual)
        self.cb__hepatit.setObjectName("cb__hepatit")
        self.cb__hepatit.addItem("")
        self.cb__hepatit.addItem("")
        self.horizontalLayout_14.addWidget(self.cb__hepatit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_onco = QtWidgets.QLabel(self.gb_manual)
        self.label_onco.setWordWrap(True)
        self.label_onco.setObjectName("label_onco")
        self.horizontalLayout_15.addWidget(self.label_onco)
        self.cb_onco = QtWidgets.QComboBox(self.gb_manual)
        self.cb_onco.setObjectName("cb_onco")
        self.cb_onco.addItem("")
        self.cb_onco.addItem("")
        self.horizontalLayout_15.addWidget(self.cb_onco)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_30.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.gb_manual)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_30.addWidget(self.line_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_hronLung = QtWidgets.QLabel(self.gb_manual)
        self.label_hronLung.setWordWrap(True)
        self.label_hronLung.setObjectName("label_hronLung")
        self.horizontalLayout_16.addWidget(self.label_hronLung)
        self.cb_hronLung = QtWidgets.QComboBox(self.gb_manual)
        self.cb_hronLung.setObjectName("cb_hronLung")
        self.cb_hronLung.addItem("")
        self.cb_hronLung.addItem("")
        self.horizontalLayout_16.addWidget(self.cb_hronLung)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_bronhAstm = QtWidgets.QLabel(self.gb_manual)
        self.label_bronhAstm.setWordWrap(True)
        self.label_bronhAstm.setObjectName("label_bronhAstm")
        self.horizontalLayout_17.addWidget(self.label_bronhAstm)
        self.cb_bronhAstm = QtWidgets.QComboBox(self.gb_manual)
        self.cb_bronhAstm.setObjectName("cb_bronhAstm")
        self.cb_bronhAstm.addItem("")
        self.cb_bronhAstm.addItem("")
        self.horizontalLayout_17.addWidget(self.cb_bronhAstm)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_tubLung = QtWidgets.QLabel(self.gb_manual)
        self.label_tubLung.setWordWrap(True)
        self.label_tubLung.setObjectName("label_tubLung")
        self.horizontalLayout_18.addWidget(self.label_tubLung)
        self.cb_tubLung = QtWidgets.QComboBox(self.gb_manual)
        self.cb_tubLung.setObjectName("cb_tubLung")
        self.cb_tubLung.addItem("")
        self.cb_tubLung.addItem("")
        self.horizontalLayout_18.addWidget(self.cb_tubLung)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_spid = QtWidgets.QLabel(self.gb_manual)
        self.label_spid.setWordWrap(True)
        self.label_spid.setObjectName("label_spid")
        self.horizontalLayout_19.addWidget(self.label_spid)
        self.cb_spid = QtWidgets.QComboBox(self.gb_manual)
        self.cb_spid.setObjectName("cb_spid")
        self.cb_spid.addItem("")
        self.cb_spid.addItem("")
        self.horizontalLayout_19.addWidget(self.cb_spid)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_12 = QtWidgets.QLabel(self.gb_manual)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_20.addWidget(self.label_12)
        self.comboBox_14 = QtWidgets.QComboBox(self.gb_manual)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.horizontalLayout_20.addWidget(self.comboBox_14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_lekHoles = QtWidgets.QLabel(self.gb_manual)
        self.label_lekHoles.setWordWrap(True)
        self.label_lekHoles.setObjectName("label_lekHoles")
        self.horizontalLayout_21.addWidget(self.label_lekHoles)
        self.cb_lekHoles = QtWidgets.QComboBox(self.gb_manual)
        self.cb_lekHoles.setObjectName("cb_lekHoles")
        self.cb_lekHoles.addItem("")
        self.cb_lekHoles.addItem("")
        self.horizontalLayout_21.addWidget(self.cb_lekHoles)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_lekInsult = QtWidgets.QLabel(self.gb_manual)
        self.label_lekInsult.setWordWrap(True)
        self.label_lekInsult.setObjectName("label_lekInsult")
        self.horizontalLayout_22.addWidget(self.label_lekInsult)
        self.cb_lekInsult = QtWidgets.QComboBox(self.gb_manual)
        self.cb_lekInsult.setObjectName("cb_lekInsult")
        self.cb_lekInsult.addItem("")
        self.cb_lekInsult.addItem("")
        self.horizontalLayout_22.addWidget(self.cb_lekInsult)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_lekDiab = QtWidgets.QLabel(self.gb_manual)
        self.label_lekDiab.setWordWrap(True)
        self.label_lekDiab.setObjectName("label_lekDiab")
        self.horizontalLayout_23.addWidget(self.label_lekDiab)
        self.cb_lekDiab = QtWidgets.QComboBox(self.gb_manual)
        self.cb_lekDiab.setObjectName("cb_lekDiab")
        self.cb_lekDiab.addItem("")
        self.cb_lekDiab.addItem("")
        self.horizontalLayout_23.addWidget(self.cb_lekDiab)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_lekAstma = QtWidgets.QLabel(self.gb_manual)
        self.label_lekAstma.setWordWrap(True)
        self.label_lekAstma.setObjectName("label_lekAstma")
        self.horizontalLayout_24.addWidget(self.label_lekAstma)
        self.cb_lekAstma = QtWidgets.QComboBox(self.gb_manual)
        self.cb_lekAstma.setObjectName("cb_lekAstma")
        self.cb_lekAstma.addItem("")
        self.cb_lekAstma.addItem("")
        self.horizontalLayout_24.addWidget(self.cb_lekAstma)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_smoking = QtWidgets.QLabel(self.gb_manual)
        self.label_smoking.setWordWrap(True)
        self.label_smoking.setObjectName("label_smoking")
        self.horizontalLayout_25.addWidget(self.label_smoking)
        self.cb_smoking = QtWidgets.QComboBox(self.gb_manual)
        self.cb_smoking.setObjectName("cb_smoking")
        self.cb_smoking.addItem("")
        self.cb_smoking.addItem("")
        self.horizontalLayout_25.addWidget(self.cb_smoking)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_percentFat = QtWidgets.QLabel(self.gb_manual)
        self.label_percentFat.setWordWrap(True)
        self.label_percentFat.setObjectName("label_percentFat")
        self.horizontalLayout_26.addWidget(self.label_percentFat)
        self.dsb_percentFat = QtWidgets.QDoubleSpinBox(self.gb_manual)
        self.dsb_percentFat.setObjectName("dsb_percentFat")
        self.horizontalLayout_26.addWidget(self.dsb_percentFat)
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_age = QtWidgets.QLabel(self.gb_manual)
        self.label_age.setWordWrap(True)
        self.label_age.setObjectName("label_age")
        self.horizontalLayout_27.addWidget(self.label_age)
        self.sb_age = QtWidgets.QSpinBox(self.gb_manual)
        self.sb_age.setMinimum(35)
        self.sb_age.setObjectName("sb_age")
        self.horizontalLayout_27.addWidget(self.sb_age)
        self.verticalLayout_4.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_30.addLayout(self.verticalLayout_4)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_30)
        self.verticalLayout_5.addWidget(self.gb_manual)
        self.gb_console = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_console.setMaximumSize(QtCore.QSize(16777215, 150))
        self.gb_console.setObjectName("gb_console")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.gb_console)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pte_console = QtWidgets.QPlainTextEdit(self.gb_console)
        self.pte_console.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pte_console.setObjectName("pte_console")
        self.horizontalLayout_32.addWidget(self.pte_console)
        self.verticalLayout_5.addWidget(self.gb_console)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gb_demo = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_demo.setObjectName("gb_demo")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.gb_demo)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pb_demo1 = QtWidgets.QPushButton(self.gb_demo)
        self.pb_demo1.setObjectName("pb_demo1")
        self.horizontalLayout_33.addWidget(self.pb_demo1)
        self.pb_demo2 = QtWidgets.QPushButton(self.gb_demo)
        self.pb_demo2.setObjectName("pb_demo2")
        self.horizontalLayout_33.addWidget(self.pb_demo2)
        self.pb_demo3 = QtWidgets.QPushButton(self.gb_demo)
        self.pb_demo3.setObjectName("pb_demo3")
        self.horizontalLayout_33.addWidget(self.pb_demo3)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_33)
        self.gridLayout.addWidget(self.gb_demo, 1, 0, 1, 1)
        heartUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(heartUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 26))
        self.menubar.setObjectName("menubar")
        heartUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(heartUI)
        self.statusbar.setObjectName("statusbar")
        heartUI.setStatusBar(self.statusbar)

        self.retranslateUi(heartUI)
        QtCore.QMetaObject.connectSlotsByName(heartUI)

    def retranslateUi(self, heartUI):
        _translate = QtCore.QCoreApplication.translate
        heartUI.setWindowTitle(_translate("heartUI", "Оценка вероятности развития ССЗ"))
        self.labelSelectModel.setText(_translate("heartUI", "Выбор модели"))
        self.selectModelBox.setItemText(0, _translate("heartUI", "ОНМК"))
        self.selectModelBox.setItemText(1, _translate("heartUI", "Стенокардия, ИБС, инфаркт"))
        self.selectModelBox.setItemText(2, _translate("heartUI", "Прочие заболевания"))
        self.selectModelBox.setItemText(3, _translate("heartUI", "Серд. недост."))
        self.selectModelBox.setItemText(4, _translate("heartUI", "Арт. гипертензия"))
        self.btnRez.setText(_translate("heartUI", "Узнать вероятность"))
        self.l_rez.setText(_translate("heartUI", "Вероятность                                                         ."))
        self.groupBox.setTitle(_translate("heartUI", "Способ ввода данных"))
        self.rb_manual.setText(_translate("heartUI", "Ручной (интерфейс)"))
        self.rb_console.setText(_translate("heartUI", "Консоль"))
        self.gb_manual.setTitle(_translate("heartUI", "Ручной интерфейс"))
        self.label_area.setText(_translate("heartUI", "Место проживания"))
        self.cb_area.setItemText(0, _translate("heartUI", "Город"))
        self.cb_area.setItemText(1, _translate("heartUI", "Село"))
        self.label_sex.setText(_translate("heartUI", "Пол"))
        self.cb_sex.setItemText(0, _translate("heartUI", "М"))
        self.cb_sex.setItemText(1, _translate("heartUI", "Ж"))
        self.label_steno.setText(_translate("heartUI", "Стенокардия, ИБС, инфаркт миокарда"))
        self.cb_steno.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_steno.setItemText(1, _translate("heartUI", "Да"))
        self.label_othHeartDes.setText(_translate("heartUI", "Прочие заболевания сердца"))
        self.cb_othHearDes.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_othHearDes.setItemText(1, _translate("heartUI", "Да"))
        self.label_heartNed.setText(_translate("heartUI", "Сердечная недостаточность"))
        self.cb_heartNed.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_heartNed.setItemText(1, _translate("heartUI", "Да"))
        self.label_artHyper.setText(_translate("heartUI", "Артериальная гипертензия"))
        self.cb_artHyper.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_artHyper.setItemText(1, _translate("heartUI", "Да"))
        self.label_educ.setText(_translate("heartUI", "Образование"))
        self.cb_educ.setItemText(0, _translate("heartUI", "Начальная школа"))
        self.cb_educ.setItemText(1, _translate("heartUI", "средняя школа / закон.среднее / выше среднего"))
        self.cb_educ.setItemText(2, _translate("heartUI", "профессиональное училище"))
        self.cb_educ.setItemText(3, _translate("heartUI", "ВУЗ"))
        self.label_ecgNorm.setText(_translate("heartUI", "ЭКГ норма"))
        self.cb_ecgNorm.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_ecgNorm.setItemText(1, _translate("heartUI", "Да"))
        self.label_regularDrug.setText(_translate("heartUI", "Регулярный прим лекарственных средств"))
        self.cb_regularDrug.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_regularDrug.setItemText(1, _translate("heartUI", "Да"))
        self.label_sugDiab.setText(_translate("heartUI", "Сахарный диабет"))
        self.cb_sugDiab.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_sugDiab.setItemText(1, _translate("heartUI", "Да"))
        self.label_hepatit.setText(_translate("heartUI", "Гепатит"))
        self.cb__hepatit.setItemText(0, _translate("heartUI", "Нет"))
        self.cb__hepatit.setItemText(1, _translate("heartUI", "Да"))
        self.label_onco.setText(_translate("heartUI", "Онкология"))
        self.cb_onco.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_onco.setItemText(1, _translate("heartUI", "Да"))
        self.label_hronLung.setText(_translate("heartUI", "Хроническое заболевание легких"))
        self.cb_hronLung.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_hronLung.setItemText(1, _translate("heartUI", "Да"))
        self.label_bronhAstm.setText(_translate("heartUI", "Бронжиальная астма"))
        self.cb_bronhAstm.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_bronhAstm.setItemText(1, _translate("heartUI", "Да"))
        self.label_tubLung.setText(_translate("heartUI", "Туберкулез легких"))
        self.cb_tubLung.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_tubLung.setItemText(1, _translate("heartUI", "Да"))
        self.label_spid.setText(_translate("heartUI", "ВИЧ/СПИД"))
        self.cb_spid.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_spid.setItemText(1, _translate("heartUI", "Да"))
        self.label_12.setText(_translate("heartUI", "Лекарство / давление"))
        self.comboBox_14.setItemText(0, _translate("heartUI", "Нет"))
        self.comboBox_14.setItemText(1, _translate("heartUI", "Да"))
        self.label_lekHoles.setText(_translate("heartUI", "Лекарство / холестерин"))
        self.cb_lekHoles.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_lekHoles.setItemText(1, _translate("heartUI", "Да"))
        self.label_lekInsult.setText(_translate("heartUI", "Лекарство / инсульт"))
        self.cb_lekInsult.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_lekInsult.setItemText(1, _translate("heartUI", "Да"))
        self.label_lekDiab.setText(_translate("heartUI", "Лекарство / диабет"))
        self.cb_lekDiab.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_lekDiab.setItemText(1, _translate("heartUI", "Да"))
        self.label_lekAstma.setText(_translate("heartUI", "Лекарство / астма"))
        self.cb_lekAstma.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_lekAstma.setItemText(1, _translate("heartUI", "Да"))
        self.label_smoking.setText(_translate("heartUI", "Статус Курения"))
        self.cb_smoking.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_smoking.setItemText(1, _translate("heartUI", "Да"))
        self.label_percentFat.setText(_translate("heartUI", "% жира"))
        self.label_age.setText(_translate("heartUI", "Возраст"))
        self.gb_console.setTitle(_translate("heartUI", "Консоль ввода данных"))
        self.gb_demo.setTitle(_translate("heartUI", "Демо данные"))
        self.pb_demo1.setText(_translate("heartUI", "Набор 1"))
        self.pb_demo2.setText(_translate("heartUI", "Набор 2"))
        self.pb_demo3.setText(_translate("heartUI", "Набор 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    heartUI = QtWidgets.QMainWindow()
    ui = Ui_heartUI()
    ui.setupUi(heartUI)
    heartUI.show()
    sys.exit(app.exec_())
