# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGui\form.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_heartUI(object):
    def setupUi(self, heartUI):
        heartUI.setObjectName("heartUI")
        heartUI.resize(1021, 728)
        self.centralwidget = QtWidgets.QWidget(heartUI)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 40, 281, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(850, 320, 73, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(830, 240, 73, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(840, 250, 73, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(850, 260, 73, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 410, 55, 16))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 420, 55, 16))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(470, 430, 55, 16))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(480, 440, 55, 16))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 70, 281, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_area = QtWidgets.QLabel(self.widget)
        self.label_area.setObjectName("label_area")
        self.horizontalLayout_2.addWidget(self.label_area)
        self.cb_area = QtWidgets.QComboBox(self.widget)
        self.cb_area.setObjectName("cb_area")
        self.cb_area.addItem("")
        self.cb_area.addItem("")
        self.horizontalLayout_2.addWidget(self.cb_area)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 100, 181, 24))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_sex = QtWidgets.QLabel(self.widget1)
        self.label_sex.setObjectName("label_sex")
        self.horizontalLayout_3.addWidget(self.label_sex)
        self.cb_sex = QtWidgets.QComboBox(self.widget1)
        self.cb_sex.setObjectName("cb_sex")
        self.cb_sex.addItem("")
        self.cb_sex.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_sex)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(10, 130, 261, 34))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_steno = QtWidgets.QLabel(self.widget2)
        self.label_steno.setWordWrap(True)
        self.label_steno.setObjectName("label_steno")
        self.horizontalLayout_4.addWidget(self.label_steno)
        self.cb_steno = QtWidgets.QComboBox(self.widget2)
        self.cb_steno.setObjectName("cb_steno")
        self.cb_steno.addItem("")
        self.cb_steno.addItem("")
        self.horizontalLayout_4.addWidget(self.cb_steno)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(10, 170, 301, 50))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_othHeartDes = QtWidgets.QLabel(self.widget3)
        self.label_othHeartDes.setWordWrap(True)
        self.label_othHeartDes.setObjectName("label_othHeartDes")
        self.horizontalLayout_5.addWidget(self.label_othHeartDes)
        self.cb_othHearDes = QtWidgets.QComboBox(self.widget3)
        self.cb_othHearDes.setObjectName("cb_othHearDes")
        self.cb_othHearDes.addItem("")
        self.cb_othHearDes.addItem("")
        self.horizontalLayout_5.addWidget(self.cb_othHearDes)
        self.widget4 = QtWidgets.QWidget(self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(20, 230, 261, 34))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_heartNed = QtWidgets.QLabel(self.widget4)
        self.label_heartNed.setWordWrap(True)
        self.label_heartNed.setObjectName("label_heartNed")
        self.horizontalLayout_6.addWidget(self.label_heartNed)
        self.cb_heartNed = QtWidgets.QComboBox(self.widget4)
        self.cb_heartNed.setObjectName("cb_heartNed")
        self.cb_heartNed.addItem("")
        self.cb_heartNed.addItem("")
        self.horizontalLayout_6.addWidget(self.cb_heartNed)
        self.widget5 = QtWidgets.QWidget(self.centralwidget)
        self.widget5.setGeometry(QtCore.QRect(10, 1, 731, 32))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelSelectModel = QtWidgets.QLabel(self.widget5)
        self.labelSelectModel.setObjectName("labelSelectModel")
        self.horizontalLayout.addWidget(self.labelSelectModel)
        self.selectModelBox = QtWidgets.QComboBox(self.widget5)
        self.selectModelBox.setEnabled(False)
        self.selectModelBox.setObjectName("selectModelBox")
        self.selectModelBox.addItem("")
        self.selectModelBox.addItem("")
        self.selectModelBox.addItem("")
        self.selectModelBox.addItem("")
        self.selectModelBox.addItem("")
        self.horizontalLayout.addWidget(self.selectModelBox)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnRez = QtWidgets.QPushButton(self.widget5)
        self.btnRez.setObjectName("btnRez")
        self.horizontalLayout_7.addWidget(self.btnRez)
        self.l_rez = QtWidgets.QLabel(self.widget5)
        self.l_rez.setObjectName("l_rez")
        self.horizontalLayout_7.addWidget(self.l_rez)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.widget6 = QtWidgets.QWidget(self.centralwidget)
        self.widget6.setGeometry(QtCore.QRect(50, 280, 144, 34))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_artHyper = QtWidgets.QLabel(self.widget6)
        self.label_artHyper.setWordWrap(True)
        self.label_artHyper.setObjectName("label_artHyper")
        self.horizontalLayout_9.addWidget(self.label_artHyper)
        self.cb_artHyper = QtWidgets.QComboBox(self.widget6)
        self.cb_artHyper.setObjectName("cb_artHyper")
        self.cb_artHyper.addItem("")
        self.cb_artHyper.addItem("")
        self.horizontalLayout_9.addWidget(self.cb_artHyper)
        heartUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(heartUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 26))
        self.menubar.setObjectName("menubar")
        heartUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(heartUI)
        self.statusbar.setObjectName("statusbar")
        heartUI.setStatusBar(self.statusbar)

        self.retranslateUi(heartUI)
        QtCore.QMetaObject.connectSlotsByName(heartUI)

    def retranslateUi(self, heartUI):
        _translate = QtCore.QCoreApplication.translate
        heartUI.setWindowTitle(_translate("heartUI", "Оценка вероятности"))
        self.comboBox_2.setItemText(0, _translate("heartUI", "Нет"))
        self.comboBox_2.setItemText(1, _translate("heartUI", "Да"))
        self.comboBox_6.setItemText(0, _translate("heartUI", "Нет"))
        self.comboBox_6.setItemText(1, _translate("heartUI", "Да"))
        self.comboBox_7.setItemText(0, _translate("heartUI", "Нет"))
        self.comboBox_7.setItemText(1, _translate("heartUI", "Да"))
        self.comboBox_8.setItemText(0, _translate("heartUI", "Нет"))
        self.comboBox_8.setItemText(1, _translate("heartUI", "Да"))
        self.label_5.setText(_translate("heartUI", "TextLabel"))
        self.label_6.setText(_translate("heartUI", "TextLabel"))
        self.label_7.setText(_translate("heartUI", "TextLabel"))
        self.label_8.setText(_translate("heartUI", "TextLabel"))
        self.label_area.setText(_translate("heartUI", "Место проживания"))
        self.cb_area.setItemText(0, _translate("heartUI", "Город"))
        self.cb_area.setItemText(1, _translate("heartUI", "Село"))
        self.label_sex.setText(_translate("heartUI", "Пол"))
        self.cb_sex.setItemText(0, _translate("heartUI", "М"))
        self.cb_sex.setItemText(1, _translate("heartUI", "Ж"))
        self.label_steno.setText(_translate("heartUI", "Стенокардия, ИБС, инфаркт миокарда"))
        self.cb_steno.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_steno.setItemText(1, _translate("heartUI", "Да"))
        self.label_othHeartDes.setText(_translate("heartUI", "Прочие заболевания сердца"))
        self.cb_othHearDes.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_othHearDes.setItemText(1, _translate("heartUI", "Да"))
        self.label_heartNed.setText(_translate("heartUI", "Сердечная недостаточность"))
        self.cb_heartNed.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_heartNed.setItemText(1, _translate("heartUI", "Да"))
        self.labelSelectModel.setText(_translate("heartUI", "Выбор модели"))
        self.selectModelBox.setItemText(0, _translate("heartUI", "ОНМК"))
        self.selectModelBox.setItemText(1, _translate("heartUI", "Стенокардия, ИБС, инфаркт"))
        self.selectModelBox.setItemText(2, _translate("heartUI", "Прочие заболевания"))
        self.selectModelBox.setItemText(3, _translate("heartUI", "Серд. недост."))
        self.selectModelBox.setItemText(4, _translate("heartUI", "Арт. гипертензия"))
        self.btnRez.setText(_translate("heartUI", "Узнать вероятность"))
        self.l_rez.setText(_translate("heartUI", "Вероятность"))
        self.label_artHyper.setText(_translate("heartUI", "Артериальная гипертензия"))
        self.cb_artHyper.setItemText(0, _translate("heartUI", "Нет"))
        self.cb_artHyper.setItemText(1, _translate("heartUI", "Да"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    heartUI = QtWidgets.QMainWindow()
    ui = Ui_heartUI()
    ui.setupUi(heartUI)
    heartUI.show()
    sys.exit(app.exec_())
